language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WvWgPC4yA6XqKO/CUyOFLL7ez676Qber18gr4bHPjsMh18+/E0vfoy2Pg3ACWkLCD2i+fo0lxe5dxzeF4Rd9Z013UnWMCjpaVndn29Fb4Tymsa7+qCj2ZwX2emVp1J2gCJg57Cd67lzs9R5bc30UIK1a3QczkspKv4UHoNUP5L3SU3L0hqu3FnLxzmfMZDSrXMY8gaDqdGqB/ag0EHRzI1+AQOxtosHXxaSLT5oodpDpzVpQKT4qLjILa6dF/KTEArWwTJa6DtM+A+aaTio8QI3qwNJgzvW7XNzsGqFOt3mbc17GKk1kJVAfl8ejNd3RSjEg9FjrwKVfTixzQML6Drz8Qo7mo6yFhJmklR4zVzR/rp+nyINmVbJYfPe64/hlXJqMitxK89HQ+6aXfAw4PvvwYaj149ZrmW7ejxE1yD508kQX3IfxTsi4qZwv0Lo4M4ahMd1NTzjH7yvaZx6s+mWX12xHhuZDC8GNgGryHiDRkTTaGrwchrsXgIbWQsZKzSTpGYBtvac+q2375u/+ahP6wzQM5Mah4v9k/1ZuvthhNNPlXa6a0+k7OnT4m8+7nluHVILSg20/Fe/JNOIYjroXmBVuoOutK3+PpR9yoG1KiM07OGd2Pm8Y5aYtfg4sz/w/JoMeUFssGKK1b8CoXO+nfQlyj07cVxoTITzOtOU="

addons:
  coverity_scan:
    project:
      name: LeFlou/Citadel
    notification_email: leflou@gmx.com
    build_command_prepend: "cmake"
    build_command:   "make"
    branch_pattern: coverity_scan

before_script:
  - cmake .

script:
  - make

branches:
  only:
    - coverity_scan
