version: 1.0.{build}
configuration: Release
platform:
- x86
- x64
build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- mkdir VS2015
- cd VS2015
- cmake -G "Visual Studio 14 2015" ..
- cmake --build . --target ALL_BUILD --config Release
build:
  verbosity: detailed