version: 1.0.{build}

image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Visual Studio 2019 Preview

configuration:
  - Release

platform:
  - x64

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G %generator%

build:
  verbosity: detailed
  parallel: true
